interface UnitMetaData {
    [key: string]: {
        cost: number
    }
}

const unitMetaData: UnitMetaData = {
    "Ahri": { cost: 2, },
    "Akali": { cost: 2, },
    "Ashe": { cost: 1, },
    "Bard": { cost: 3, },
    "Briar": { cost: 5, },
    "Camille": { cost: 5, },
    "Cassio": { cost: 2, },
    "Diana": { cost: 5, },
    "Elise": { cost: 1, },
    "Ezreal": { cost: 3, },
    "Fiora": { cost: 4, },
    "Galio": { cost: 2, },
    "Gwen": { cost: 4, },
    "Hecarim": { cost: 3, },
    "Hwei": { cost: 3, },
    "Jax": { cost: 1, },
    "Jayce": { cost: 1, },
    "Jinx": { cost: 1, },
    "Kalista": { cost: 4, },
    "Karma": { cost: 4, },
    "Kassadin": { cost: 2, },
    "Katarina": { cost: 3, },
    "KogMaw": { cost: 2, },
    "Lillia": { cost: 1, },
    "Milio": { cost: 5, },
    "Mord": { cost: 3, },
    "Morgana": { cost: 5, },
    "Nami": { cost: 4, },
    "Nasus": { cost: 4, },
    "Neeko": { cost: 3, },
    "Nilah": { cost: 2, },
    "Nomsy": { cost: 1, },
    "Norra": { cost: 5, },
    "Nunu": { cost: 2, },
    "Olaf": { cost: 4, },
    "Poppy": { cost: 1, },
    "Rakan": { cost: 4, },
    "Rumble": { cost: 2, },
    "Ryze": { cost: 4, },
    "Seraphine": { cost: 1, },
    "Shen": { cost: 3, },
    "Shyvana": { cost: 2, },
    "Smolder": { cost: 5, },
    "Soraka": { cost: 1, },
    "Swain": { cost: 3, },
    "Syndra": { cost: 2, },
    "Tahm": { cost: 4, },
    "Taric": { cost: 4, },
    "Tristana": { cost: 2, },
    "Twitch": { cost: 1, },
    "Varus": { cost: 4, },
    "Veigar": { cost: 3, },
    "Vex": { cost: 3, },
    "Warwick": { cost: 1, },
    "Wukong": { cost: 3, },
    "Xerath": { cost: 5, },
    "Ziggs": { cost: 1, },
    "Zilean": { cost: 2, },
    "Zoe": { cost: 1, },
}

export default unitMetaData;
